# Generated by Django 5.0.3 on 2024-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('image_source', models.CharField(max_length=15)),
            ],
        ),
    ]
