# Generated by Django 4.2.4 on 2023-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('sport', models.CharField(max_length=30)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
